export const ALL_WALLETS_REQUEST = 'ALL_WALLETS_REQUEST';
export const ALL_WALLETS_SUCCESS = 'ALL_WALLETS_SUCCESS';
export const ALL_WALLETS_FAIL = 'ALL_WALLETS_FAIL';

export const CREATE_WALLET_REQUEST = 'CREATE_WALLET_REQUEST';
export const CREATE_WALLET_SUCCESS = 'CREATE_WALLET_SUCCESS';
export const CREATE_WALLET_FAIL = 'CREATE_WALLET_FAIL';

export const MAKE_DEPOSIT_REQUEST = 'MAKE_DEPOSIT_REQUEST';
export const MAKE_DEPOSIT_SUCCESS = 'MAKE_DEPOSIT_SUCCESS';
export const MAKE_DEPOSIT_FAIL = 'MAKE_DEPOSIT_FAIL';

export const MAKE_WITHDRAWAL_REQUEST = 'MAKE_WITHDRAWAL_REQUEST';
export const MAKE_WITHDRAWAL_SUCCESS = 'MAKE_WITHDRAWAL_SUCCESS';
export const MAKE_WITHDRAWAL_FAIL = 'MAKE_WITHDRAWAL_FAIL';

export const MAKE_TRANSFER_REQUEST = 'MAKE_TRANSFER_REQUEST';
export const MAKE_TRANSFER_SUCCESS = 'MAKE_TRANSFER_SUCCESS';
export const MAKE_TRANSFER_FAIL = 'MAKE_TRANSFER_FAIL';
